complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 10
    thresholdInObjects: 10

style:
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '100'
      - '1000'
  ReturnCount:
    active: true
    max: 3

potential-bugs:
  UnsafeCallOnNullableType:
    active: true
  LateinitUsage:
    active: true

security:
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  ExposedContentProviderSql:
    active: true
  FilePermission:
    active: true
  CertificateCheck:
    active: true
  HardcodedKey:
    active: true
  InsecureRandom:
    active: true
  SQLInjection:
    active: true
  SSLCertificateVerification:
    active: true
  InvalidCipherMode:
    active: true
  WebViewJavascriptEnabled:
    active: true
