build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    complexity: 2
    formatting: 1
    style: 1
    comments: 1
    security: 3

config:
  validation: true
  warningsAsErrors: true

processors:
  active: true

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FileBasedFindingsReport'

output-reports:
  active: true
  exclude: []

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: true
  CommentOverPrivateProperty:
    active: true
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  NestedBlockDepth:
    active: true
    threshold: 4
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 10
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
  MemberNameEqualsClassName:
    active: true
  ObjectExtendsThrowable:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: true
  TooGenericExceptionThrown:
    active: true

formatting:
  active: true
  android: false
  autoCorrect: true

naming:
  active: true
  FunctionMaxLength:
    active: true
    maximumFunctionNameLength: 40
  FunctionMinLength:
    active: true
    minimumFunctionNameLength: 3
  VariableMaxLength:
    active: true
    maximumVariableNameLength: 40
  VariableMinLength:
    active: true
    minimumVariableNameLength: 2

performance:
  active: true
  SpreadOperator:
    active: true

potential-bugs:
  active: true
  DuplicateCaseInWhenExpression:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: false
  MapGetWithNotNullAssertionOperator:
    active: true
  NullableToStringCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnreachableCode:
    active: true
  UnsafeCast:
    active: true
  UselessPostfixExpression:
    active: true

security:
  active: true
  AllowedDataClasses:
    active: true
    allowedTypes:
      - 'kotlin.collections.List'
      - 'kotlin.collections.MutableList'
      - 'kotlin.collections.Set'
      - 'kotlin.collections.MutableSet'
      - 'kotlin.collections.Map'
      - 'kotlin.collections.MutableMap'
      - 'retrofit2.Response'
  CryptoKeyGeneration:
    active: true
  DeserialisationInsecurity:
    active: true
  FragmentInjection:
    active: true
  HardcodedApiSecret:
    active: true
  HardcodedApiUrl:
    active: true
  ImplicitExternalContentAccessibility:
    active: true
  InsecureRuntimeExecutable:
    active: true
  LeakingContentProvider:
    active: true
  LeakingServiceConnection:
    active: true
  NoExternalFilesDir:
    active: true
  NoFilenameHardcoding:
    active: true
  NoHardcodedCredentials:
    active: true
  NoInheritFromRoot:
    active: true
  NoMessageChainInspection:
    active: true
  PublicActivityContracts:
    active: true
  SQLInjection:
    active: true
  UnsafeImportStarredSecurity:
    active: true
  UnsafeLoggingPII:
    active: true
  UnsafeRandomProvider:
    active: true
  VulnerableBroadcastReceiver:
    active: true
  WebViewInsecurity:
    active: true

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  MagicNumber:
    active: true
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '100'
      - '1000'
  ReturnCount:
    active: true
    max: 3
  ThrowsCount:
    active: true
    max: 2
  UnusedPrivateMember:
    active: true
  WildcardImport:
    active: true
