name: Security Scanning

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  mobsfscan:
    name: MobSF Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run MobSF scan
        uses: MobSF/mobsfscan-action@main
        with:
          output-format: json
          output-file: mobsf-scan-results.json
          exit-on: security

      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: mobsfscan-results
          path: mobsf-scan-results.json

  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Semgrep scan
        run: |
          semgrep ci --config=p/android --config=p/secrets --config=p/kotlin \
          --json > semgrep-results.json

      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: semgrep-results.json

  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run OWASP Dependency Check
        run: ./gradlew dependencyCheckAggregate

      - name: Upload dependency check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: build/reports/dependency-check-report.html

  trivy-scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  security-report:
    name: Generate Security Report
    needs: [mobsfscan, semgrep, dependency-check, trivy-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all scan results
        uses: actions/download-artifact@v3

      - name: Generate consolidated report
        run: |
          echo "# Security Scan Report" > security-report.md
          echo "Generated on: $(date)" >> security-report.md
          echo "" >> security-report.md
          
          echo "## MobSF Scan" >> security-report.md
          echo "See attachment: mobsfscan-results.json" >> security-report.md
          echo "" >> security-report.md
          
          echo "## Semgrep Analysis" >> security-report.md
          echo "See attachment: semgrep-results.json" >> security-report.md
          echo "" >> security-report.md
          
          echo "## OWASP Dependency Check" >> security-report.md
          echo "See attachment: dependency-check-report.html" >> security-report.md
          echo "" >> security-report.md
          
          echo "## Trivy Scan" >> security-report.md
          echo "See attachment: trivy-results.sarif" >> security-report.md

      - name: Upload consolidated report
        uses: actions/upload-artifact@v3
        with:
          name: consolidated-security-report
          path: security-report.md
